In [1]:
import pandas as pd
from sqlalchemy import create_engine, URL, text
from getpass import getpass

# Weather Data Cleaning/Inspection

In [2]:
weather_data = pd.read_csv("newark_airport_2016.csv")

print(weather_data.head()) #Successful import

       STATION                                         NAME        DATE  \
0  USW00014734  NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US  2016-01-01
1  USW00014734  NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US  2016-01-02
2  USW00014734  NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US  2016-01-03
3  USW00014734  NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US  2016-01-04
4  USW00014734  NEWARK LIBERTY INTERNATIONAL AIRPORT, NJ US  2016-01-05

    AWND  PGTM  PRCP  SNOW  SNWD  TAVG  TMAX  TMIN  TSUN  WDF2   WDF5  WSF2  \
0  12.75   NaN   0.0   0.0   0.0    41    43    34   NaN   270  280.0  25.9
1   9.40   NaN   0.0   0.0   0.0    36    42    30   NaN   260  260.0  21.0
2  10.29   NaN   0.0   0.0   0.0    37    47    28   NaN   270  250.0  23.9
3  17.22   NaN   0.0   0.0   0.0    32    35    14   NaN   330  330.0  25.9
4   9.84   NaN   0.0   0.0   0.0    19    31    10   NaN   360  350.0  25.1

   WSF5
0  35.1
1  25.1
2  30.0
3  33.1
4  31.1

In [3]:
weather_data.describe()

,AWND,PGTM,PRCP,SNOW,SNWD,TAVG,TMAX,TMIN,TSUN,WDF2,WDF5,WSF2,WSF5
count,366.000000,0.0,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,0.0,366.000000,364.000000,366.000000,364.000000
mean,9.429973,NaN,0.104945,0.098087,0.342623,57.196721,65.991803,48.459016,NaN,217.841530,228.269231,20.484426,26.801648
std,3.748174,NaN,0.307496,1.276498,2.078510,17.466981,18.606301,17.135790,NaN,102.548282,97.415777,6.848390,8.882610
min,2.460000,NaN,0.000000,0.000000,0.000000,8.000000,18.000000,0.000000,NaN,10.000000,10.000000,6.900000,10.100000
25%,6.765000,NaN,0.000000,0.000000,0.000000,43.000000,51.250000,35.000000,NaN,150.000000,150.000000,15.000000,19.900000
50%,8.720000,NaN,0.000000,0.000000,0.000000,56.000000,66.000000,47.000000,NaN,240.000000,260.000000,19.900000,25.100000
75%,11.410000,NaN,0.030000,0.000000,0.000000,74.000000,83.000000,64.000000,NaN,300.000000,300.000000,23.900000,31.100000
max,22.820000,NaN,2.790000,24.000000,20.100000,89.000000,99.000000,80.000000,NaN,360.000000,360.000000,48.100000,66.000000

In [4]:
weather_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 16 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STATION  366 non-null    str
 1   NAME     366 non-null    str
 2   DATE     366 non-null    str
 3   AWND     366 non-null    float64
 4   PGTM     0 non-null      float64
 5   PRCP     366 non-null    float64
 6   SNOW     366 non-null    float64
 7   SNWD     366 non-null    float64
 8   TAVG     366 non-null    int64
 9   TMAX     366 non-null    int64
 10  TMIN     366 non-null    int64
 11  TSUN     0 non-null      float64
 12  WDF2     366 non-null    int64
 13  WDF5     364 non-null    float64
 14  WSF2     366 non-null    float64
 15  WSF5     364 non-null    float64
dtypes: float64(9), int64(4), str(3)
memory usage: 45.9 KB

In [5]:
weather_data = weather_data.drop(columns=["PGTM", "TSUN"])

weather_data.columns

Index(['STATION', 'NAME', 'DATE', 'AWND', 'PRCP', 'SNOW', 'SNWD', 'TAVG',
       'TMAX', 'TMIN', 'WDF2', 'WDF5', 'WSF2', 'WSF5'],
      dtype='str')

# Citibike Data Cleaning/Inspection

In [6]:
jan_data = pd.read_csv("JC-201601-citibike-tripdata.csv")
feb_data = pd.read_csv("JC-201602-citibike-tripdata.csv")
mar_data = pd.read_csv("JC-201603-citibike-tripdata.csv")
apr_data = pd.read_csv("JC-201604-citibike-tripdata.csv")
may_data = pd.read_csv("JC-201605-citibike-tripdata.csv")
jun_data = pd.read_csv("JC-201606-citibike-tripdata.csv")
jul_data = pd.read_csv("JC-201607-citibike-tripdata.csv")
aug_data = pd.read_csv("JC-201608-citibike-tripdata.csv")
sep_data = pd.read_csv("JC-201609-citibike-tripdata.csv")
oct_data = pd.read_csv("JC-201610-citibike-tripdata.csv")
nov_data = pd.read_csv("JC-201611-citibike-tripdata.csv")
dec_data = pd.read_csv("JC-201612-citibike-tripdata.csv")

full_year_list = [jan_data, feb_data, mar_data, apr_data, may_data, jun_data, jul_data, aug_data, sep_data, oct_data, nov_data, dec_data]

combined_df = pd.concat(full_year_list, ignore_index=True)

In [7]:
print(combined_df.head())

   Trip Duration           Start Time            Stop Time  Start Station ID  \
0            362  2016-01-01 00:02:52  2016-01-01 00:08:54              3186
1            200  2016-01-01 00:18:22  2016-01-01 00:21:42              3186
2            202  2016-01-01 00:18:25  2016-01-01 00:21:47              3186
3            248  2016-01-01 00:23:13  2016-01-01 00:27:21              3209
4            903  2016-01-01 01:03:20  2016-01-01 01:18:24              3195

  Start Station Name  Start Station Latitude  Start Station Longitude  \
0      Grove St PATH               40.719586               -74.043117
1      Grove St PATH               40.719586               -74.043117
2      Grove St PATH               40.719586               -74.043117
3       Brunswick St               40.724176               -74.050656
4            Sip Ave               40.730743               -74.063784

   End Station ID End Station Name  End Station Latitude  \
0            3209     Brunswick St             40.724176
1            3213   Van Vorst Park             40.718489
2            3213   Van Vorst Park             40.718489
3            3203    Hamilton Park             40.727596
4            3210   Pershing Field             40.742677

   End Station Longitude  Bike ID   User Type  Birth Year  Gender
0             -74.050656    24647  Subscriber      1964.0       2
1             -74.047727    24605  Subscriber      1962.0       1
2             -74.047727    24689  Subscriber      1962.0       2
3             -74.044247    24693  Subscriber      1984.0       1
4             -74.051789    24573    Customer         NaN       0

In [8]:
print(combined_df.isna().sum()) #When customer is not a subscriber the company does not have birthyear on account

Trip Duration                  0
Start Time                     0
Stop Time                      0
Start Station ID               0
Start Station Name             0
Start Station Latitude         0
Start Station Longitude        0
End Station ID                 0
End Station Name               0
End Station Latitude           0
End Station Longitude          0
Bike ID                        0
User Type                    380
Birth Year                 18999
Gender                         0
dtype: int64

In [9]:
print(combined_df.shape) # 247,584 rows & 16 columns

(247584, 15)

In [10]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 247584 entries, 0 to 247583
Data columns (total 15 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Trip Duration            247584 non-null  int64
 1   Start Time               247584 non-null  str
 2   Stop Time                247584 non-null  str
 3   Start Station ID         247584 non-null  int64
 4   Start Station Name       247584 non-null  str
 5   Start Station Latitude   247584 non-null  float64
 6   Start Station Longitude  247584 non-null  float64
 7   End Station ID           247584 non-null  int64
 8   End Station Name         247584 non-null  str
 9   End Station Latitude     247584 non-null  float64
 10  End Station Longitude    247584 non-null  float64
 11  Bike ID                  247584 non-null  int64
 12  User Type                247204 non-null  str
 13  Birth Year               228585 non-null  float64
 14  Gender                   247584 non-null  int64
dtypes: float64(5), int64(5), str(5)
memory usage: 28.3 MB

In [11]:
combined_df.describe()

,Trip Duration,Start Station ID,Start Station Latitude,Start Station Longitude,End Station ID,End Station Latitude,End Station Longitude,Bike ID,Birth Year,Gender
count,2.475840e+05,247584.000000,247584.000000,247584.000000,247584.000000,247584.000000,247584.000000,247584.000000,228585.000000,247584.000000
mean,8.856305e+02,3207.065206,40.723121,-74.046438,3203.572553,40.722594,-74.045855,24935.260481,1979.335276,1.123534
std,3.593798e+04,26.955103,0.008199,0.011211,61.579494,0.007958,0.011283,748.469712,9.596809,0.518687
min,6.100000e+01,3183.000000,40.692640,-74.096937,147.000000,40.692216,-74.096937,14552.000000,1900.000000,0.000000
25%,2.480000e+02,3186.000000,40.717732,-74.050656,3186.000000,40.716540,-74.050444,24491.000000,1974.000000,1.000000
50%,3.900000e+02,3201.000000,40.721525,-74.044247,3199.000000,40.721124,-74.043117,24609.000000,1981.000000,1.000000
75%,6.660000e+02,3211.000000,40.727596,-74.038051,3211.000000,40.727224,-74.036486,24719.000000,1986.000000,1.000000
max,1.632981e+07,3426.000000,40.752559,-74.032108,3426.000000,40.801343,-73.957390,27274.000000,2000.000000,2.000000

In [12]:
combined_df = combined_df.dropna(subset=["User Type"])

print(combined_df.isna().sum())

Trip Duration                  0
Start Time                     0
Stop Time                      0
Start Station ID               0
Start Station Name             0
Start Station Latitude         0
Start Station Longitude        0
End Station ID                 0
End Station Name               0
End Station Latitude           0
End Station Longitude          0
Bike ID                        0
User Type                      0
Birth Year                 18999
Gender                         0
dtype: int64

## Establishing a SQL Connection

In [13]:
# Note that this is GPT code (I was never taught to connect to databases, So I simply used ChatGPT as a resource)

db_password = getpass("PostgreSQL password: ")

connection_url = URL.create(
    drivername="postgresql+psycopg2",
    username="postgres",
    password=db_password,
    host="localhost",
    port=5432,
    database="bike_rentals"
)

engine = create_engine(connection_url)

PostgreSQL password:  ········

In [14]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT current_database(), current_user")
    )
    print(result.fetchone())

('bike_rentals', 'postgres')

## Reshaping data For SQL

In [15]:
renamed_combined_df = combined_df.rename(columns={"Trip Duration": "trip_duration", "Start Time": "start_time", "Stop Time": "stop_time", "Start Station ID": "start_station_id", "Start Station Name": "start_station_name", "Start Station Latitude": "start_station_latitude", "Start Station Longitude": "start_station_longitude", "End Station ID": "end_station_id", "End Station Name": "end_station_name", "End Station Latitude": "end_station_latitude", "End Station Longitude": "end_station_longitude", "Bike ID": "bike_id", "User Type": "user_type", "Birth Year": "birth_year", "Gender": "gender"})

In [21]:
sql_weather_df = weather_data.rename(columns={"STATION": "station", "NAME": "name", "DATE": "date", "AWND": "awnd", "PRCP": "prcp", "SNOW": "snow", "SNWD": "snwd", "TAVG": "tavg", "TMAX": "tmax", "TMIN": "tmin", "WDF2": "wdf2", "WDF5": "wdf5", "WSF2": "wsf2", "WSF5": "wsf5"})

#to_sql would not work without data being lowercase Even with uppercase SQL designations, So I changed over the necessary letters.

In [17]:
#sql_bike_data_1 = renamed_combined_df[["trip_duration", "bike_id", "user_type", "birth_year", "gender"]].copy()

#sql_bike_data_2 = renamed_combined_df[["start_time", "stop_time", "start_station_id", "start_station_name", "start_station_latitude", "start_station_longitude", "end_station_id", "end_station_name", "end_station_latitude", "end_station_longitude"]].copy()

In [22]:
print(sql_weather_df.columns.tolist())
#print(sql_bike_data_1.columns.tolist())
#print(sql_bike_data_2.columns.tolist())

['station', 'name', 'date', 'awnd', 'prcp', 'snow', 'snwd', 'tavg', 'tmax', 'tmin', 'wdf2', 'wdf5', 'wsf2', 'wsf5']

Decided to not go with seperate tables for bike data after some more deep thinking. Instead I will rename the columns properly and keep the original structure of the bike rental data.

In [23]:
sql_weather_df.to_sql(name="weather_data", con=engine, if_exists="append", index=False)

366

In [25]:
renamed_combined_df.to_sql(name="bike_rental_data", con=engine, if_exists="append", index=False)

204

In [27]:
with engine.connect() as connection:
    bike_count = connection.execute(
        text("SELECT COUNT(*) FROM bike_rental_data")
    ).scalar()

    weather_count = connection.execute(
        text("SELECT COUNT(*) FROM weather_data")
    ).scalar()

print("Bike trip rows:", bike_count) #Dropped 380 rows earlier
print("Weather rows:", weather_count)

Bike trip rows: 247204
Weather rows: 366